# Generated by Django 2.1.1 on 2018-09-18 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cellphone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='Invalid Cellphone Number', message='Cellphone Number format [09xx-xxxxxxx].', regex='(09)\\d{2}-\\d{7}$')]),
        ),
    ]
