# Generated by Django 2.1.1 on 2018-09-18 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180918_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cellphone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='Invalid Cellphone Number', message='Cellphone Number format [0917xxxxxxx].', regex='(09)\\d{2}-\\d{7}$')]),
        ),
    ]
