# Generated by Django 2.1.1 on 2018-09-18 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180918_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cellphone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='Invalid Cellphone Number', message='Cellphone Number format [0917xxxxxxx].', regex='(09)\\d{9}$')]),
        ),
    ]
